# SOME NUMPY COMPUTATIONAL FUCTIONS

### 5 Numpy amazing functions you will like to know

**Numpy is a numerical computational python library used for data analysis having amazing functions to play around in order to achieve a desire output. Below are five choosen functions you will need to know about

1. Trigeometric Functions
2. Rounding Functions
3. Stacking Functions
4. Statistical Functions
5. Linear algebra and Matrix Library


**pi function can be call using numpy.pi or can be import from numpy module as seen below  

In [1]:
import numpy as np
from numpy import pi

Function 1. Trigeometric Function is a scientific function used to determine value for angle and viseversa. we have the sin(), cos(), tan(), arcsin() cot() functions. pi/180 is use to convert degrees into radians

In [87]:
angles = np.array([0,30,60,120,150,180,360])

In [88]:
#Example 1 Sine
np.sin(angles * pi/180) #in radians

In [90]:
#Example 2 Cosine
np.cos(angles* pi/180)

array([ 1.       ,  0.8660254,  0.5      , -0.5      , -0.8660254,
       -1.       ,  1.       ])

In [91]:
#Example 3 Tangent
np.tan(angles*pi/180)

array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00, -1.73205081e+00,
       -5.77350269e-01, -1.22464680e-16, -2.44929360e-16])

In [92]:
#example 4 Breaking: When sqaure bracket is use for trig functions it report an error
np.sin[angles*pi/180]

TypeError: 'numpy.ufunc' object is not subscriptable

**Function 2: Round functions**
This functions is use to round up numbers and decimals to suit your output. At default is 0 and if its negative, it round to the left of the number

In [94]:
#Example 1 at default
unrounded = np.array([23.168, 2.950, 150, 9.567])
print("Before rounding up")
print(unrounded)
print("After rounded to 0")
print(np.around(unrounded))

Before rounding up
[ 23.168   2.95  150.      9.567]
After rounded to 0
[ 23.   3. 150.  10.]


In [96]:
#Example 2: At 2 decimal
np.around(unrounded, decimals = 2)

array([ 23.17,   2.95, 150.  ,   9.57])

In [100]:
#Example 3: At Negative decimal
np.around(unrounded, decimals = -1)

array([ 20.,   0., 150.,  10.])

In [101]:
#Example 4: Break. Be mindful of the spelling of decimal as the aurgument of decimal 
#        must appear in plural and not square bracket
np.around(unrounded, decimal= -1)

TypeError: _around_dispatcher() got an unexpected keyword argument 'decimal'

##### Function 3: Stacking Function.
*** The Stacking is use to stack together two or more arrays. Its another way of concetenating arrays. We have the hstack() and column_stack() which stacking on column axis. The vstack() and row_stack() which stacking on the row axis. vstack is an alias for row_stack which make them the same 

In [105]:
a = np.array([[2,6], [10,3], [9,0]])

In [104]:
b = np.array([[5,7],[4,7], [1,8]])

In [106]:
#Example 1. horizontal stack
np.hstack((a,b))

array([[ 2,  6,  5,  7],
       [10,  3,  4,  7],
       [ 9,  0,  1,  8]])

In [107]:
#Example 2. column stack

np.column_stack((a,b))

array([[ 2,  6,  5,  7],
       [10,  3,  4,  7],
       [ 9,  0,  1,  8]])

In [108]:
#Example 3. vertical stack
np.vstack((a,b))

array([[ 2,  6],
       [10,  3],
       [ 9,  0],
       [ 5,  7],
       [ 4,  7],
       [ 1,  8]])

In [109]:
#Example 3. row stack
np.row_stack((a,b))

array([[ 2,  6],
       [10,  3],
       [ 9,  0],
       [ 5,  7],
       [ 4,  7],
       [ 1,  8]])

In [114]:
#Example 4. Breaking: To stack the array, they must have the same dimension
c =  np.array([[2,3],[4,6]])
np.hstack((a,c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

**Function 4: Statistics Function**
Numpy is also used to solve statistic problem such as minimum, maximum, variance, standard deviation and so on. 

In [5]:
#Example 1: amin() function is use to find the minimum value at a specific axis

stat_value = np.array([[12, 4, 5],
                       [6, 9, 1],
                       [10, 7, 2]])
print("minimum without axis")
print(np.amin(stat_value))

print("minimum at axis 0")
print(np.amin(stat_value, axis = 0))

print("minimum at axis 1")
print(np.amin(stat_value, axis = 1))




minimum without axis
1
minimum at axis 0
[6 4 1]
minimum at axis 1
[4 1 2]


In [7]:
#Example 2: amax() function gives the maximum value at a given axis. At defualt is gives 
#the maximum of the total elements
print("maximum without axis i.e(of the total elements)")
print(np.amax(stat_value))

print("maximum at axis 0 i.e(of each row)")
print(np.amax(stat_value, axis = 0))

print("maximum at axis 1 i.e(of each column)")
print(np.amax(stat_value, axis = 1))



maximum without axis
12
maximum at axis 0
[12  9  5]
maximum at axis 1
[12  9 10]


In [8]:
#Breaking of amin() and amax() occur when the specify axis = array's dimension. 
#Forinstance our array is 2D and therefore the axis cannot be >=2
print(np.amin(stat_value, axis=2))

print(np.amax(stat_value, axis = 2))




AxisError: axis 2 is out of bounds for array of dimension 2

In [13]:
#Example 3: Percentile() function use to determine the value of a given data on a given percent. it must be compute within 0-100
print("original array \n", stat_value)
print("50% of the whole element \n", np.percentile(stat_value,50))
print('\n')
print("50% at axis = 0 i.e each row elements \n", np.percentile(stat_value,50, axis = 0))
print('\n')
print("50% at axis = 1 i.e each column elements \n", np.percentile(stat_value,50, axis = 1))



original array 
 [[12  4  5]
 [ 6  9  1]
 [10  7  2]]
50% of the whole element 
 6.0


50% at axis = 0 i.e each row elements 
 [10.  7.  2.]


50% at axis = 1 i.e each column elements 
 [5. 6. 7.]


In [14]:
#Breaking Percentile return error when the range is above 100

np.percentile(stat_value,120, axis = 0)


ValueError: Percentiles must be in the range [0, 100]

In [15]:
#Example 3: Standard deviation std() is an square root of the average of square deviations from mean
# and variance is the average of square deviation. 
print("standard deviation at axis = 0 i.e each row elements \n", np.std(stat_value, axis = 0))
print('\n')
print("variance at axis =  0 i.e each row elements \n", np.var(stat_value, axis = 0))


standard deviation at axis = 0 i.e each row elements 
 [2.49443826 2.05480467 1.69967317]


variance at axis =  0 i.e each row elements 
 [6.22222222 4.22222222 2.88888889]


##### Mean(), Median(), decile(), average() and so many statistical functions can be calculated using numpy.

**Function 5: Linear Algebra & Matrix Module**
NumPy package contains a Matrix library numpy.matlib. This module has functions that return matrices instead of ndarray objects. It is import from numpy library. It functions and operations similar to ndarray just it returns matrices instead of ndarray objects and the dimension of matrix is always 2D whereas ndarrays is n-dimentions
functions such as np.matlib.identity(), np.matlib.empty(), np.matlib.ones(), np.matlib.zeros() and many more can be found in numpy matrix library

In [40]:
import numpy.matlib as mat

In [76]:
a = [[1, 4], [5, 8]]

In [87]:
a = np.array(a)

In [47]:
#Example 1: matlib.eye(n, M, k, dtpye). n = column, M = rows, k = index

mat.eye(n=3, M=4, k=1)

matrix([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [48]:
#Breaking: the letter 'n and k' must be lowercase while letter 'M' must be uppercase

mat.eye(N=3, M=4, k=1) #'N' changed to uppercase

TypeError: eye() got an unexpected keyword argument 'N'

In [86]:

b = [[2, 1], [10, 9]]
b = np.array(b)

In [88]:
#Example 2: vector dot and matrix dot
print("matrix dot product of matrices a and b")
print(mat.dot(a, b))
print('\n')
print("vector dot product of matrix a and b")
np.vdot(a, b)


matrix dot product of matrices a and b
[[42 37]
 [90 77]]


vector dot product of matrix a and b


128

In [67]:
#Example 3: Determinant function is determine using the np.linalg.det() function
np.linalg.det([[3, 4, 5],[6, 4, 2],[9, 1, 7]])

-168.0000000000001

In [89]:
#Example 4: The numpy.linalg.solve() function gives the solution of linear equations 
#in the matrix form (Ax - B = 0)
a = [[3, 4, 5],[6, 4, 2],[9, 1, 7]]
b = [[2, 1],[7, 0],[5, 6]]
np.linalg.solve(a, b)

array([[ 1.00595238,  0.27380952],
       [ 0.57142857, -0.71428571],
       [-0.66071429,  0.60714286]])

In [73]:
#Example 5. Breaking: The shape of the two matrices at axis 0 must be the same 
#i.e They must have the same number of rows
a = [[3, 4, 5],[6, 4, 2],[9, 1, 7]]
b = [[2, 1],[7, 0]]
np.linalg.solve(a, b)

ValueError: solve: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m,n)->(m,n) (size 2 is different from 3)

### We have seen some lengthy and useful functions and module Numpy can provide. A lot of numerical analysis can be achieve using numpy as seen from above. 

***references
> https://numpy.org/doc/stable/reference
>https://www.tutorialspoint.com/numpy