## NAME: MUFTAHU ABDULRAHMAN (ACE22110008)
## COURSE: PROGRAMMING FOR AI (ATI803)
## ASSIGNMENT TITLE: WORKING WITH NUMPY
### To be submitted on 16/05/2022

### Question 1a
### Write a python code that create a 4X3 integer array from a range between 10 to 70 such that the difference between each element is 5.

In [1]:
# Importing Numpy lirary
import numpy as np

In [4]:
# Creating thr range of array and reshaping to get the desire dimension
range_array = np.array(range(10,70,5)).reshape(4,3)

In [5]:
# Displaying the array
range_array

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65]])

### Question 1b
### b)	Given an array sampleArray below: sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]).
### Write a python code that returns an array of odd rows and even columns. The output should look like:[[ 6 12][30 36][54 60]]


In [28]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
# Double slicing on rows and columns
OddEvenArray = sampleArray[::2, 1::2]

# Displaying the results
print("The output of odd Rows and Even columns are")
print(OddEvenArray)

The output of odd Rows and Even columns are
[[ 6 12]
 [30 36]
 [54 60]]


### Question 2a
### 2.	a) Given the following arrays: 
### arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
### arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]]) 

### i.	Create another array called result by adding arrayOne and arrayTwo. 
### ii.	Modify the result array by calculating the square of each element:


In [11]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

# Adding the two Arrays
result = np.add(arrayOne,arrayTwo)

# Squaring the result
modify_result = np.square(result)

In [12]:
print("The result of adding the two arrays is")
print(result, "\n")

print("The square of the result is")
print(modify_result)

The result of adding the two arrays is
[[20 39 33]
 [25 25 28]] 

The square of the result is
[[ 400 1521 1089]
 [ 625  625  784]]


### Question 2b
### b) Given the array sampleArray below:
### sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 
### Write a python code that deletes the second column from the given sampleArray and insert the following new column in its place. newColumn = numpy.array([[10,10,10]])

In [20]:
# Sample array
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

# We delete the second column by direct replacement with desire array.
newColumn = np.array([[10,10,10]])

# Replacing the second column with newColumn array
sampleArray[:, 1] = newColumn

print("sampleArray after deleting & replacing the second column")
print(sampleArray)

sampleArray after deleting & replacing the second column
[[34 10 73]
 [82 10 12]
 [53 10 66]]
